
"use client";
import {useState} from "react"; 
// self care tips generated by perplexity 
const selfcare_tips=[
    "Hydrate with Love: Allow yourself to drink plenty of water throughout the day, feeling refreshed with each sip. You might even add slices of cucumber for a delightful twist.", 
    "Move with Ease: Engage in gentle exercises like yoga or a peaceful walk, allowing your body to flow with grace and harmony.", 
    "Mindful Moments: Take a few moments each day to breathe deeply and meditate, letting go of worries and embracing calmness.", 
    "Gratitude Reflections: Write down the things you're grateful for, allowing positivity to fill your heart and mind.",
    "Connect with Kindness: Reach out to loved ones and nurture those connections, feeling supported and loved.",
    "Creative Expression: Engage in activities like drawing, crafting, or cooking, letting your creativity flow and calm your spirit."
];

export default function SelfCare() {
    const [index,setIndex] = useState(0); 
    const nextTip = () =>{
        setIndex((current) => (current+1));
    };
    const prevTip = () =>{
        setIndex((current) => (current-1));
    };
    return (
        <div>
            <h2 className="text-4xl mt-0 m-1 mb-0">self-care</h2>
            <div className="p-2 text-[#39777A]">
                {selfcare_tips[index]}
                <button className="m-4 float-left text-[#B0C4B1]" onClick={prevTip}> &lt; </button>
                <button className="m-4 float-right text-[#B0C4B1]" onClick={nextTip}> &gt; </button>
            </div>
        </div>
    )
}